# Generated by Django 3.2.12 on 2022-03-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_code', models.CharField(max_length=10)),
                ('m_name', models.CharField(max_length=60)),
                ('m_year', models.IntegerField()),
                ('m_semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(max_length=10)),
                ('p_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_rate', to='pages.module')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_rate', to='pages.professor')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='prof_module',
            field=models.ManyToManyField(to='pages.Professor'),
        ),
    ]
