# Generated by Django 3.2.12 on 2022-03-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_module_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('m_code', 'm_name', 'm_year', 'm_semester')},
        ),
    ]
